import { useState, useEffect } from 'react';
import { Service, Booking, BusinessProfile, Provider } from './types';
import { useBusiness } from './hooks/useBusiness';
import { useServices } from './hooks/useServices';
import { useBookings } from './hooks/useBookings';
import { usePiAuth } from './hooks/usePiAuth';
import { usePullToRefresh } from './hooks/usePullToRefresh';
import { bookingService } from './services/bookingService';
import { Navbar } from './components/Navbar';
import { Footer } from './components/Footer';
import { PullToRefreshIndicator } from './components/PullToRefreshIndicator';
import { ServiceBrowser } from './components/ServiceBrowser';
import { SearchView } from './components/SearchView';
import { ServiceDetail } from './components/ServiceDetail';
import { SelectDetailsStep } from './components/SelectDetailsStep';
import { SelectScheduleStep } from './components/SelectScheduleStep';
import { BookingSummaryStep } from './components/BookingSummaryStep';
import { PiPaymentModal } from './components/PiPaymentModal';
import { BookingConfirmationStep } from './components/BookingConfirmationStep';
import { BookingStatusView } from './components/BookingStatusView';
import { PublicProfileView } from './components/PublicProfileView';
import { BecomeProviderStep, BecomeProviderDetails } from './components/BecomeProviderStep';
import { BecomeProviderModal } from './components/BecomeProviderModal';
import { ProviderDashboardView } from './features/provider/ProviderDashboardView';
import { providerService } from './services/providerService';
import { ThemeService } from './services/themeService';
import { settingsService } from './services/settingsService';

type FlowStep = 'browse'|'about'|'detail'|'select_details'|'select_schedule'|'review_summary'|'payment'|'confirmation'|'status'|'become_provider'|'provider_console';

export default function App() {
  const { business, loading: loadingBusiness, refreshBusiness } = useBusiness();
  const { services, refreshServices } = useServices();
  const { bookings, refreshBookings } = useBookings();
  const { piUser, loading: piAuthLoading, signIn: signInWithPi, signOut: signOutPi } = usePiAuth();
  const [activeTab, setActiveTab] = useState<'browse'|'search'|'bookings'>('browse');
  const [currentFlow, setCurrentFlow] = useState<FlowStep>('browse');
  const [searchQuery, setSearchQuery] = useState('');
  const [searchCategory, setSearchCategory] = useState('all');
  const [selectedService, setSelectedService] = useState<Service|null>(null);
  const [selectedDate, setSelectedDate] = useState('');
  const [selectedTimeSlot, setSelectedTimeSlot] = useState('');
  const [clientDetails, setClientDetails] = useState<{clientName:string;clientPiUsername:string;clientPhone:string;notes:string;attachments?:{id:string;name:string;size:string;type:string;dataUrl?:string}[]}>({clientName:'',clientPiUsername:'',clientPhone:'',notes:'',attachments:[]});
  const [confirmedBooking, setConfirmedBooking] = useState<Booking|null>(null);
  const [selectedProfile, setSelectedProfile] = useState<BusinessProfile|Provider|null>(null);
  const [myProviderId, setMyProviderId] = useState<string|null>(null);
  const [providerCheckDone, setProviderCheckDone] = useState(false);
  const [showBecomeProviderModal, setShowBecomeProviderModal] = useState(false);
  const [becomeProviderPopupEnabled, setBecomeProviderPopupEnabled] = useState(false);
  const [hasDismissedProviderModal, setHasDismissedProviderModal] = useState(() => sessionStorage.getItem('pibooking_dismissed_provider_modal') === 'true');
  const [isSubmittingProvider, setIsSubmittingProvider] = useState(false);
  const handleRefreshAll = async () => { await Promise.all([refreshBusiness(), refreshServices(), refreshBookings()]); };
  const { isPulling, isRefreshing, pullDistance, pullProgress, isThresholdReached } = usePullToRefresh({
    onRefresh: handleRefreshAll,
  });
  useEffect(() => { settingsService.getSettings().then((settings) => setBecomeProviderPopupEnabled(settings.become_provider_popup_enabled)); }, []);
  useEffect(() => { ThemeService.initTheme(); }, []);
  useEffect(() => { const scrollToTop=()=>{window.scrollTo({top:0,left:0,behavior:'instant' as ScrollBehavior});document.documentElement.scrollTop=0;document.body.scrollTop=0;const mainEl=document.querySelector('main');if(mainEl)mainEl.scrollTop=0;};scrollToTop();const frameId=requestAnimationFrame(scrollToTop);return()=>cancelAnimationFrame(frameId); }, [activeTab,currentFlow,selectedService?.id,(selectedProfile as any)?.id]);
  useEffect(() => { if(!piUser)return;setClientDetails((prev)=>({...prev,clientPiUsername:piUser.username?(piUser.username.startsWith('@')?piUser.username:`@${piUser.username}`):prev.clientPiUsername})); }, [piUser]);
  useEffect(() => { if(!piUser?.uid){setMyProviderId(null);setProviderCheckDone(false);return;} providerService.getProviderByPiUid(piUser.uid).then((provider)=>{setMyProviderId(provider?provider.id:null);setProviderCheckDone(true);}); }, [piUser]);
  useEffect(() => { if(!becomeProviderPopupEnabled||!piUser?.uid||!providerCheckDone||myProviderId!==null||hasDismissedProviderModal)return;const timer=setTimeout(()=>{if(becomeProviderPopupEnabled&&piUser?.uid&&myProviderId===null&&!hasDismissedProviderModal)setShowBecomeProviderModal(true);},7000);return()=>clearTimeout(timer); }, [becomeProviderPopupEnabled,piUser,providerCheckDone,myProviderId,hasDismissedProviderModal]);
  const handleDismissProviderModal=()=>{setShowBecomeProviderModal(false);setHasDismissedProviderModal(true);sessionStorage.setItem('pibooking_dismissed_provider_modal','true');};
  const handleOpenBecomeProvider=()=>{setActiveTab('browse');setCurrentFlow('become_provider');};
  const handleSubmitProvider=async(details:BecomeProviderDetails)=>{if(!piUser?.uid||!piUser.accessToken)return;setIsSubmittingProvider(true);try{const created=await providerService.addProvider({fullName:details.fullName,piUsername:details.piUsername||undefined,piUid:piUser.uid,roleTitle:details.roleTitle,headline:details.headline||undefined,bio:details.bio,photoUrl:details.photoUrl||undefined,piWalletAddress:details.piWalletAddress||undefined,location:details.location||undefined,specialties:details.specialties||[],skills:details.skills||[],experienceLevel:details.experienceLevel||undefined,yearsExperience:details.yearsExperience||undefined,availabilityStatus:details.availabilityStatus||'available',responseTime:details.responseTime||undefined,languages:details.languages||[],serviceMode:details.serviceMode||undefined,website:details.website||undefined,portfolioImages:details.portfolioImages||[],portfolioItems:details.portfolioItems||[],status:'Approved'},piUser.accessToken);setMyProviderId(created.id);setCurrentFlow('browse');}finally{setIsSubmittingProvider(false);}};
  const handleSelectService=(service:Service)=>{setActiveTab('browse');setSelectedService(service);setCurrentFlow('detail');};
  const handleOpenSearch=(query?:string,category?:string)=>{setSearchQuery(query||'');setSearchCategory(category||'all');setActiveTab('search');};
  const handleStartBooking=()=>{setActiveTab('browse');setCurrentFlow('select_details');};
  const handleConfirmDetails=(details:any)=>{setActiveTab('browse');setClientDetails(details);setCurrentFlow('select_schedule');};
  const handleConfirmSchedule=(date:string,timeSlot:string)=>{setActiveTab('browse');setSelectedDate(date);setSelectedTimeSlot(timeSlot);setCurrentFlow('review_summary');};
  const handleProceedToPayment=()=>{setActiveTab('browse');setCurrentFlow('payment');};
  const handlePaymentSuccess=async(newBooking:Booking)=>{setActiveTab('browse');const created=await bookingService.saveBookingAsync({...newBooking,escrow_status:'paid_escrowed',paid_at:new Date().toISOString()});setConfirmedBooking(created);await handleRefreshAll();setCurrentFlow('confirmation');};
  const handleGoToMyBookings=()=>{setActiveTab('bookings');setCurrentFlow('status');};
  const handleCancelBooking=async(bookingId:string)=>{await bookingService.updateBookingStatusAsync(bookingId,'Cancelled');await refreshBookings();};
  const handleRescheduleBooking=(booking:Booking)=>{setActiveTab('browse');if(business){const srv=services.find((s)=>s.id===booking.serviceId)||services[0];setSelectedService(srv);setCurrentFlow('select_details');}};
  const handleConfirmCompletion=async(bookingId:string)=>{await bookingService.updateBookingEscrowStatusAsync(bookingId,'completion_confirmed');await refreshBookings();};
  const handleAcceptBooking=async(bookingId:string)=>{await bookingService.updateBookingStatusAsync(bookingId,'In Progress');await refreshBookings();};
  const handleRejectBooking=async(bookingId:string,reason:string,payoutTxHash?:string)=>{await bookingService.updateBookingStatusAsync(bookingId,'Cancelled',reason,payoutTxHash);await refreshBookings();};
  const handleNavigateHome=()=>{setActiveTab('browse');setCurrentFlow('browse');};
  const handleNavigateSearch=()=>{setActiveTab('search');};
  const handleNavigateBookings=()=>{setActiveTab('bookings');setCurrentFlow('status');};
  const handleOpenAboutBusiness=()=>{setActiveTab('browse');setSelectedProfile(businessWithServices);setCurrentFlow('about');};
  const businessWithServices={...business,services};
  if(loadingBusiness&&!business)return <div className="min-h-screen bg-white flex flex-col items-center justify-center p-4 text-center space-y-3"><div className="w-8 h-8 rounded-full border-2 border-amber-500 border-t-transparent animate-spin mx-auto"/><span className="text-xs font-bold text-zinc-600">Loading Pi Business OS...</span></div>;
  return <div className="min-h-screen w-full flex flex-col bg-white text-zinc-900 font-sans selection:bg-amber-500 selection:text-white transition-colors overflow-x-hidden"><PullToRefreshIndicator isPulling={isPulling} isRefreshing={isRefreshing} pullDistance={pullDistance} pullProgress={pullProgress} isThresholdReached={isThresholdReached}/><Navbar currentBusiness={businessWithServices} piUser={piUser} piAuthLoading={piAuthLoading} onSignIn={signInWithPi} onSignOut={signOutPi} hasProvider={!!myProviderId} onOpenBecomeProvider={handleOpenBecomeProvider} onOpenProviderConsole={()=>{setActiveTab('browse');setCurrentFlow('provider_console');}} activeTab={activeTab} currentFlow={currentFlow} bookingsCount={bookings.filter((b)=>piUser&&(b.clientPiUsername===`@${piUser.username}`||b.clientPiUsername===piUser.username)&&(b.status==='Confirmed'||b.status==='In Progress')).length} onNavigateHome={handleNavigateHome} onNavigateSearch={handleNavigateSearch} onNavigateBookings={handleNavigateBookings} onOpenAboutBusiness={handleOpenAboutBusiness}/><main className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6 flex-1">{activeTab==='search'?<SearchView services={services} onSelectService={handleSelectService} initialQuery={searchQuery} initialCategory={searchCategory}/>:activeTab==='browse'?(currentFlow==='browse'?<ServiceBrowser business={businessWithServices} services={services} onSelectService={handleSelectService} onOpenAbout={(merchant)=>{setSelectedProfile(merchant||null);setCurrentFlow('about');}} onOpenSearch={handleOpenSearch}/>:currentFlow==='about'?<PublicProfileView merchant={selectedProfile||businessWithServices} services={services} onBack={()=>setCurrentFlow('browse')} onSelectService={handleSelectService}/>:currentFlow==='detail'&&selectedService?<ServiceDetail service={selectedService} business={businessWithServices} onBack={()=>setCurrentFlow('browse')} onProceedToBooking={handleStartBooking}/>:currentFlow==='select_details'&&selectedService?<SelectDetailsStep service={selectedService} initialDetails={clientDetails} onBack={()=>setCurrentFlow('detail')} onProceedToSchedule={handleConfirmDetails}/>:currentFlow==='select_schedule'&&selectedService?<SelectScheduleStep service={selectedService} initialDate={selectedDate} initialTimeSlot={selectedTimeSlot} onBack={()=>setCurrentFlow('select_details')} onConfirmSchedule={handleConfirmSchedule}/>:currentFlow==='review_summary'&&selectedService?<BookingSummaryStep service={selectedService} business={businessWithServices} selectedDate={selectedDate} selectedTimeSlot={selectedTimeSlot} clientDetails={clientDetails} piUser={piUser} onBack={()=>setCurrentFlow('select_schedule')} onProceedToPayment={handleProceedToPayment}/>:currentFlow==='payment'&&selectedService?<PiPaymentModal service={selectedService} business={businessWithServices} date={selectedDate} timeSlot={selectedTimeSlot} clientDetails={clientDetails} piUser={piUser} onBack={()=>setCurrentFlow('review_summary')} onPaymentComplete={handlePaymentSuccess}/>:currentFlow==='confirmation'&&confirmedBooking?<BookingConfirmationStep booking={confirmedBooking} onGoToBookings={handleGoToMyBookings}/>:currentFlow==='become_provider'?<BecomeProviderStep piUser={piUser} onBack={()=>setCurrentFlow('browse')} onSubmit={handleSubmitProvider} submitting={isSubmittingProvider}/>:currentFlow==='provider_console'?<ProviderDashboardView piUser={piUser} providerId={myProviderId||''} bookings={bookings} onBack={()=>setCurrentFlow('browse')} onAcceptBooking={handleAcceptBooking} onRejectBooking={handleRejectBooking} onProviderUpdated={handleRefreshAll}/>:<ServiceBrowser business={businessWithServices} services={services} onSelectService={handleSelectService} onOpenAbout={(merchant)=>{setSelectedProfile(merchant||null);setCurrentFlow('browse');}}/>):<BookingStatusView bookings={bookings.filter((b)=>piUser&&(b.clientPiUsername===`@${piUser.username}`||b.clientPiUsername===piUser.username))} onBrowseServices={()=>{setActiveTab('browse');setCurrentFlow('browse')}} onCancelBooking={handleCancelBooking} onRescheduleBooking={handleRescheduleBooking} onAddReview={bookingService.submitBookingReviewAsync} onConfirmCompletion={handleConfirmCompletion}/>}</main>{(activeTab==='search'||activeTab==='bookings'||(activeTab==='browse'&&currentFlow==='browse'))&&<Footer currentBusiness={businessWithServices}/>}<BecomeProviderModal isOpen={showBecomeProviderModal} onClose={handleDismissProviderModal} onBecomeProvider={handleOpenBecomeProvider}/></div>;
}

